pom.xml
src/main/java/me/makkuusen/timing/system/ApiUtilities.java
src/main/java/me/makkuusen/timing/system/CommandHeat.java
src/main/java/me/makkuusen/timing/system/CommandTrack.java
src/main/java/me/makkuusen/timing/system/Database.java
src/main/java/me/makkuusen/timing/system/DatabaseTrack.java
src/main/java/me/makkuusen/timing/system/TSListener.java
src/main/java/me/makkuusen/timing/system/Tasks.java
src/main/java/me/makkuusen/timing/system/event/Event.java
src/main/java/me/makkuusen/timing/system/heat/Lap.java
src/main/java/me/makkuusen/timing/system/participant/Driver.java
src/main/java/me/makkuusen/timing/system/timetrial/TimeTrial.java
src/main/java/me/makkuusen/timing/system/track/Track.java
src/main/java/me/makkuusen/timing/system/track/TrackCuboidRegion.java
src/main/java/me/makkuusen/timing/system/track/TrackPolyRegion.java
src/main/java/me/makkuusen/timing/system/track/TrackRegion.java

Added support for poly regions

---

src/main/java/me/makkuusen/timing/system/TSListener.java
src/main/java/me/makkuusen/timing/system/timetrial/TimeTrial.java

If no endregion exists then the startregion will also act as an endregion. (Minimally tested time trailing and solo event)

Making endregion optional

---

src/main/java/me/makkuusen/timing/system/CommandTimeTrial.java
src/main/java/me/makkuusen/timing/system/CommandTrack.java

Attempt to add /tt random which kinda works.
Also disabled the ability to create a track named "random" (that might break something if it was allowed)

Addition of /tt random

---

src/main/java/me/makkuusen/timing/system/CommandTimeTrial.java
src/main/java/me/makkuusen/timing/system/CommandTrack.java
src/main/resources/en_us.yml

Random teleport message which displays when a player teleports to a random track.
Lang file addition
```
timer:
randomTrack: '&2Teleported you to &a%track% &2(&a#%pos%&2).'
```

Random Teleport Message

---

src/main/java/me/makkuusen/timing/system/ApiUtilities.java
src/main/java/me/makkuusen/timing/system/CommandTimeTrial.java
src/main/java/me/makkuusen/timing/system/CommandTrack.java
src/main/resources/en_us.yml
src/main/resources/sv_se.yml

Fixed an error when you `/tt random` but there are no tracks.
Moved illegal track names to api utilities class (idk where else to put them).
Changed language file and added _swedish translations_.

Random track fix and stuff

---

src/main/java/me/makkuusen/timing/system/CommandHeat.java
src/main/java/me/makkuusen/timing/system/heat/Heat.java

Reverse grid prototype. You simply use the command and the grid reverses hopefully I haven't tested much.
`/heat reversegrid <heat>`

Potential Reverse Grid Thingy

---

src/main/java/me/makkuusen/timing/system/ApiUtilities.java
src/main/java/me/makkuusen/timing/system/CommandTimeTrial.java
src/main/java/me/makkuusen/timing/system/Database.java
src/main/java/me/makkuusen/timing/system/TPlayer.java
src/main/java/me/makkuusen/timing/system/timetrial/TimeTrial.java

Adds `/tt sound` which toggles the pb sound. Setting is stored in ts_players : ttSound.
Testing may still be needed.
Closes #97 
Databases will need to run the following statement for this update to work:
``ALTER TABLE `ts_players` ADD `ttSound` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'true' AFTER `boat`;``

TimeTrail Sound Setting

---

src/main/java/me/makkuusen/timing/system/heat/ScoreboardUtils.java

Leaderboard position colour changes based on position,
Player name colour changes based on finish state,
Pit counter colour changes based on pits completed compared to pits set in a heat.

Small Scoreboard Visual Update

---

src/main/java/me/makkuusen/timing/system/heat/ScoreboardUtils.java

Fixed ugly colours.
Format pos instead of name.
Messy code idk how to fix

SCoreBoard Visual Update 2

---

src/main/java/me/makkuusen/timing/system/CommandHeat.java

Adds `/heat sort tt <heat>` and `/heat sort random <heat>`
Might also wanna take a look into optimising the tt sort
Relates to #85

Sort heats by TT or Random

---

src/main/java/me/makkuusen/timing/system/heat/ScoreboardUtils.java

EvilScientist requested this soo here it is:
> 0 pits is red, 1 or more pit is orange, and fully completed pits is green

Update Pit Colouring

---

src/main/java/me/makkuusen/timing/system/TimingSystem.java
src/main/java/me/makkuusen/timing/system/commands/CommandTrackExchange.java
src/main/java/me/makkuusen/timing/system/track/TrackDatabase.java
src/main/java/me/makkuusen/timing/system/track/TrackExchangeTrack.java
src/main/resources/plugin.yml

Track Exchange allows for saving tracks and an associated and optional schematic.
This still needs testing and cleaning up.
Closes #258

Track Exchange Feature

---

src/main/java/me/makkuusen/timing/system/api/events/HeatFinishEvent.java
src/main/java/me/makkuusen/timing/system/heat/Heat.java

Add HeatFinish Event

---

src/main/java/me/makkuusen/timing/system/participant/Driver.java

Fix /round results error

---

src/main/java/me/makkuusen/timing/system/commands/CommandTrack.java
src/main/java/me/makkuusen/timing/system/heat/FinalHeat.java
src/main/java/me/makkuusen/timing/system/track/Track.java
src/main/java/me/makkuusen/timing/system/track/TrackLocation.java

Teleport Players on Final Heat Finish

---

src/main/java/me/makkuusen/timing/system/commands/CommandTrack.java
src/main/java/me/makkuusen/timing/system/gui/TrackGui.java
src/main/java/me/makkuusen/timing/system/track/Track.java
src/main/java/me/makkuusen/timing/system/track/TrackDatabase.java
src/main/java/me/makkuusen/timing/system/track/TrackExchangeTrack.java

Allow for multiple owners per track

---

src/main/java/me/makkuusen/timing/system/event/EventDatabase.java

@JustBru00 let me know if this fixes #277

Prevent Creation of Events During Loading

---

src/main/java/me/makkuusen/timing/system/api/TimingSystemAPI.java

Add Event, Round and Heat methods to API

---

src/main/resources/plugin.yml

- Added missing permission to eventhoster.
- Added a general admin pack.

Packs update

---

src/main/java/me/makkuusen/timing/system/ApiUtilities.java
src/main/java/me/makkuusen/timing/system/Database.java
src/main/java/me/makkuusen/timing/system/commands/CommandTrack.java
src/main/java/me/makkuusen/timing/system/gui/TrackGui.java
src/main/java/me/makkuusen/timing/system/permissions/PermissionTrack.java
src/main/java/me/makkuusen/timing/system/theme/messages/Gui.java
src/main/java/me/makkuusen/timing/system/track/Track.java
src/main/java/me/makkuusen/timing/system/track/TrackDatabase.java
src/main/java/me/makkuusen/timing/system/track/TrackExchangeTrack.java
src/main/resources/lang/en_us.yml
src/main/resources/plugin.yml

Replace multiple owners with track contributors.
The following SQL statements must be run before using this version (if the server was running a 1.9 dev version before):
```sql
UPDATE `ts_tracks` SET `uuid` = SUBSTRING_INDEX(`uuid`, ',', 1) WHERE `uuid` LIKE '%,%';
ALTER TABLE `ts_tracks` ADD `contributors` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL AFTER `uuid`;
```

Track Contributors

---

src/main/java/me/makkuusen/timing/system/track/Track.java

Prevent the contributors column from having empty fields instead of null fields.

Fix contributors loading error

---

src/main/java/me/makkuusen/timing/system/TPlayer.java
src/main/java/me/makkuusen/timing/system/TimingSystem.java
src/main/java/me/makkuusen/timing/system/boatutils/BoatUtilsManager.java
src/main/java/me/makkuusen/timing/system/boatutils/BoatUtilsMode.java
src/main/java/me/makkuusen/timing/system/commands/CommandTrack.java

This also hides unavailable boat modes in tab /b mode tab completions if a player's mod is outdated.

Update to OBU 0.3

---

src/main/java/me/makkuusen/timing/system/commands/CommandTrackExchange.java
src/main/java/me/makkuusen/timing/system/track/TrackDatabase.java
src/main/java/me/makkuusen/timing/system/track/TrackExchangeTrack.java

This would make it easier to update trackexchange in the future :heart_eyes:

Switch to class serialization for trackexchange

---

src/main/java/me/makkuusen/timing/system/database/MySQLDatabase.java
src/main/java/me/makkuusen/timing/system/database/SQLiteDatabase.java
src/main/java/me/makkuusen/timing/system/database/TrackDatabase.java
src/main/java/me/makkuusen/timing/system/track/TrackCuboidRegion.java
src/main/java/me/makkuusen/timing/system/track/TrackExchangeTrack.java
src/main/java/me/makkuusen/timing/system/track/TrackPolyRegion.java
src/main/java/me/makkuusen/timing/system/track/TrackRegion.java
src/main/resources/config.yml
src/main/resources/plugin.yml

Replacing the old versioning system with a single integer that can be incremented at anytime between versions.
Setting version in SQLite to be an integer from the beginning, as it should not be containing any "1.X" versions.

New database update system
